### ISSUE TITLE
YunoHost >= 12.0.0 but current installed version is 11.2.30.2

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/vaultwarden_ynh#268]
### Describe the bug

new version fo the package is not usable with main stable ynh 

#### yunohost app upgrade vaultwarden gives:
```
Info: Now upgrading vaultwarden…
Error: This app requires YunoHost >= 12.0.0 but current installed version is 11.2.30.2
```
### Context

- Hardware: VPS
- YunoHost version: 
```
# yunohost  --version
yunohost: 
  repo: stable
  version: 11.2.30.2
yunohost-admin: 
  repo: stable
  version: 11.2.8
moulinette: 
  repo: stable
  version: 11.2.1
ssowat: 
  repo: stable
  version: 11.2.1.1
```
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- trying to install package version/branch:
```
1.32.0~ynh1 
```
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*
```
# yunohost app info vaultwarden
description: Manage passwords and other sensitive informations
domain_path: vault.krashboyz.org/
name: Vaultwarden
version: 1.29.1~ynh4
```
### Steps to reproduce
```
# yunohost app upgrade vaultwarden
```
### Expected behavior

working with stable main ynh version, or  ynh main stable > 12

### Logs

(everything is above)
